[package]
org = "ballerina"
name = "email"
version = "2.8.0"
authors = ["Ballerina"]
keywords = ["email", "SMTP", "POP", "POP3", "IMAP", "mail"]
repository = "https://github.com/ballerina-platform/module-ballerina-email"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "com.sun.mail"
artifactId = "javax.mail"
version = "1.6.2"
path = "./lib/javax.mail-1.6.2.jar"

[[platform.java17.dependency]]
groupId = "com.icegreen"
artifactId = "greenmail"
version = "1.5.11"
path = "./lib/greenmail-1.5.11.jar"

[[platform.java17.dependency]]
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"
path = "./lib/mimepull-1.9.11.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "email-native"
version = "2.8.0"
path = "../native/build/libs/email-native-2.8.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "email-test-utils"
version = "2.8.0"
path = "../test-utils/build/libs/email-test-utils-2.8.0-SNAPSHOT.jar"
scope = "testOnly"
