[plugin]
id = "email-compiler-plugin"
class = "io.ballerina.stdlib.email.compiler.EmailCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/email-compiler-plugin-2.12.0-SNAPSHOT.jar"
